/**
 * A rotating cast of well-known Rust types for the landing page to show off.
 *
 * Every path here was checked to resolve through ferritin (`ferritin get <path>`)
 * so the cycling example on the home page never lands on a broken link — if you
 * add one, verify it resolves before committing. Ordered loosely std → ecosystem;
 * the component shuffles on mount, so the list order is only for editing comfort.
 */
export const FAMOUS_TYPES = [
  // std / core / alloc
  "std::vec::Vec",
  "std::collections::HashMap",
  "std::collections::BTreeMap",
  "std::collections::HashSet",
  "std::collections::BTreeSet",
  "std::collections::VecDeque",
  "std::string::String",
  "std::option::Option",
  "std::result::Result",
  "std::boxed::Box",
  "std::rc::Rc",
  "std::sync::Arc",
  "std::sync::Mutex",
  "std::sync::RwLock",
  "std::sync::mpsc::Sender",
  "std::sync::atomic::AtomicUsize",
  "std::cell::RefCell",
  "std::cell::Cell",
  "std::cell::UnsafeCell",
  "std::path::PathBuf",
  "std::path::Path",
  "std::borrow::Cow",
  "std::fmt::Display",
  "std::fmt::Debug",
  "std::fmt::Formatter",
  "std::iter::Iterator",
  "std::convert::From",
  "std::convert::TryFrom",
  "std::convert::AsRef",
  "std::ops::Deref",
  "std::ops::Drop",
  "std::ops::Fn",
  "std::marker::PhantomData",
  "std::marker::Send",
  "std::marker::Sync",
  "std::time::Duration",
  "std::time::Instant",
  "std::time::SystemTime",
  "std::net::TcpStream",
  "std::net::TcpListener",
  "std::net::SocketAddr",
  "std::fs::File",
  "std::io::Read",
  "std::io::Write",
  "std::io::BufReader",
  "std::io::Error",
  "std::pin::Pin",
  "std::future::Future",
  "std::hash::Hash",
  "std::hash::Hasher",
  "std::cmp::Ordering",
  "std::cmp::PartialEq",
  "std::num::NonZeroU32",
  "std::num::Wrapping",
  "std::ffi::CString",
  "std::ffi::OsString",
  "std::mem::ManuallyDrop",
  "std::process::Command",
  "std::thread::JoinHandle",
  "std::error::Error",
  // serde
  "serde::Serialize",
  "serde::Deserialize",
  "serde::Serializer",
  "serde::Deserializer",
  "serde_json::Value",
  "serde_json::Map",
  // async runtimes (a light touch — the ecosystem is bigger than one runtime)
  "tokio::sync::Mutex",
  "tokio::task::JoinHandle",
  "tokio::runtime::Handle",
  "futures::Stream",
  "futures::StreamExt",
  "smol::Executor",
  "async_channel::Sender",
  // error handling
  "anyhow::Error",
  "thiserror::Error",
  "eyre::Report",
  "miette::Diagnostic",
  // CLI & terminal UI
  "clap::Parser",
  "clap::Subcommand",
  "ratatui::Terminal",
  "crossterm::event::KeyEvent",
  "console::Term",
  // parsing & macros
  "nom::IResult",
  "winnow::Parser",
  "pest::Parser",
  "regex::Regex",
  "regex::RegexSet",
  "syn::Type",
  "proc_macro2::TokenStream",
  // http, web & databases
  "axum::Router",
  "reqwest::Client",
  "http::StatusCode",
  "sqlx::Pool",
  // data, math & science
  "polars::frame::DataFrame",
  "ndarray::Array2",
  "nalgebra::Vector3",
  "glam::Vec3",
  "glam::Mat4",
  "num::BigInt",
  "half::f16",
  "ordered_float::OrderedFloat",
  // graphics, games & images
  "bevy_ecs::world::World",
  "egui::Ui",
  "wgpu::Device",
  "image::DynamicImage",
  // collections & small buffers
  "indexmap::IndexMap",
  "dashmap::DashMap",
  "hashbrown::HashMap",
  "arrayvec::ArrayVec",
  "tinyvec::TinyVec",
  "bstr::BString",
  "bstr::ByteSlice",
  // concurrency
  "rayon::iter::ParallelIterator",
  "crossbeam::channel::Sender",
  "parking_lot::Mutex",
  "arc_swap::ArcSwap",
  "governor::RateLimiter",
  "moka::sync::Cache",
  // builders, derives & schemas
  "bon::Builder",
  "typed_builder::TypedBuilder",
  "derive_builder::Builder",
  "schemars::JsonSchema",
  // everyday utility crates
  "chrono::DateTime",
  "time::OffsetDateTime",
  "uuid::Uuid",
  "rand::Rng",
  "rand::rngs::ThreadRng",
  "url::Url",
  "semver::Version",
  "semver::VersionReq",
  "tracing::Span",
  "tracing_subscriber::fmt::Subscriber",
  "once_cell::sync::Lazy",
  "itertools::Itertools",
  "petgraph::graph::DiGraph",
  "tempfile::TempDir",
  "walkdir::WalkDir",
  "flate2::read::GzDecoder",
  "sha2::Sha256",
  "toml::Value",
  // ferritin's own neighbourhood
  "trillium::Conn",
  "trillium::Handler",
] as const;
