/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/crates/{crate_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Structured documentation model for an item path. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Item path, `::`-joined (e.g. `serde::Deserialize`). */
                    crate_name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The resolved item model. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JsonItem"];
                    };
                };
                /** @description No item resolved; "did you mean" suggestions returned. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JsonNotFound"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/{crate_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search for items within a single crate. */
        get: {
            parameters: {
                query: {
                    /** @description Search query. */
                    q: string;
                };
                header?: never;
                path: {
                    /** @description Crate to search (optionally `name@version`). */
                    crate_name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Search results. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JsonSearch"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/typeahead": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Crate-name typeahead: the top crates (by download rank) whose names start with the query prefix. */
        get: {
            parameters: {
                query: {
                    /** @description Crate name prefix. */
                    q: string;
                    /** @description Maximum results (default 10, capped at 100). */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Typeahead results, in rank order. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JsonTypeahead"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Heading level for semantic structure
         * @enum {string}
         */
        HeadingLevel: "Title" | "Section";
        /**
         * @description A directly-queried trait associated item (type or const). Its own kind is
         *     serialized as `assocKind` to avoid colliding with the `JsonBody` `kind` tag.
         */
        JsonAssocItem: {
            /** @description `"type"` or `"const"`. */
            assocKind: string;
            /**
             * @description For an assoc type: whether it has a default; for an assoc const: whether
             *     it has a value.
             */
            hasDefault?: boolean;
            name: string;
            signature: components["schemas"]["JsonSpan"][];
        };
        JsonBody: ({
            /** @enum {string} */
            kind: "struct";
        } & components["schemas"]["JsonStruct"]) | ({
            /** @enum {string} */
            kind: "enum";
        } & components["schemas"]["JsonEnum"]) | ({
            /** @enum {string} */
            kind: "trait";
        } & components["schemas"]["JsonTrait"]) | ({
            /** @enum {string} */
            kind: "module";
        } & components["schemas"]["JsonModule"]) | ({
            /** @enum {string} */
            kind: "function";
        } & components["schemas"]["JsonFunction"]) | ({
            /** @enum {string} */
            kind: "typeAlias";
        } & components["schemas"]["JsonTypeAlias"]) | ({
            /** @enum {string} */
            kind: "constant";
        } & components["schemas"]["JsonConstant"]) | ({
            /** @enum {string} */
            kind: "static";
        } & components["schemas"]["JsonStatic"]) | ({
            /** @enum {string} */
            kind: "macro";
        } & components["schemas"]["JsonMacro"]) | ({
            /** @enum {string} */
            kind: "union";
        } & components["schemas"]["JsonUnion"]) | ({
            /** @enum {string} */
            kind: "assocItem";
        } & components["schemas"]["JsonAssocItem"]) | {
            /** @enum {string} */
            kind: "presentation";
            nodes: components["schemas"]["JsonNode"][];
        };
        /**
         * @description A span in a syntax-highlighted code block: a slice of source and its lexical
         *     class (`keyword`, `type`, `string`, …). Distinct from [`JsonSpan`], whose
         *     `style` is a semantic, navigable [`SpanStyle`]; a code-block class is a purely
         *     lexical highlight the client colors, with no navigation.
         */
        JsonCodeSpan: {
            class?: string | null;
            text: string;
        };
        /** @description A constant body: name, type, and optional value expression. */
        JsonConstant: {
            name: string;
            type: components["schemas"]["JsonSpan"][];
            value?: string | null;
        };
        JsonCrate: {
            description?: string | null;
            isDefault?: boolean;
            isWorkspace?: boolean;
            name: string;
            usedBy?: string[];
            version: string;
        };
        JsonEnum: {
            generics?: components["schemas"]["JsonSpan"][];
            methods?: components["schemas"]["JsonMethod"][];
            name: string;
            traitImpls?: components["schemas"]["JsonTraitImpl"][];
            variants?: components["schemas"]["JsonVariant"][];
            whereClause?: components["schemas"]["JsonSpan"][];
        };
        JsonField: {
            docs?: components["schemas"]["JsonNode"][];
            /**
             * Format: uint
             * @description Positional index, for tuple-struct fields.
             */
            index?: number | null;
            /** @description Field name, for plain-struct fields. */
            name?: string | null;
            pub: boolean;
            type: components["schemas"]["JsonSpan"][];
        };
        /**
         * @description A free function body. Mirrors [`JsonMethod`] minus the assoc-item
         *     `kind`/`visibility` and per-item `docs` — params live inside `signature`, so
         *     a function and a method serialize the same way.
         */
        JsonFunction: {
            isAsync?: boolean;
            isConst?: boolean;
            isUnsafe?: boolean;
            name: string;
            /** @description Return-type spans (functions with an explicit output). */
            returns?: components["schemas"]["JsonSpan"][];
            /** @description Full display signature, the same spans the terminal renders. */
            signature: components["schemas"]["JsonSpan"][];
        };
        JsonImplAssocType: {
            name: string;
            type: components["schemas"]["JsonSpan"][];
        };
        /**
         * @description A trait implementor: the implementing type plus the impl's structured
         *     metadata (richer than the terminal, which shows the type and assoc types).
         */
        JsonImplementor: {
            assocTypes?: components["schemas"]["JsonImplAssocType"][];
            blanket?: components["schemas"]["JsonSpan"][];
            docs?: components["schemas"]["JsonNode"][];
            /** @description The implementing type, bounds merged inline (`BufReader<R: Read>`). */
            forType: components["schemas"]["JsonSpan"][];
            isSynthetic?: boolean;
            isUnsafe?: boolean;
            methods?: components["schemas"]["JsonMethod"][];
            providedMethods?: string[];
            typeName?: string | null;
            typeUrl?: string | null;
        };
        JsonItem: {
            body: components["schemas"]["JsonBody"];
            /** @description Canonical URL for this item (its docs.rs / std-docs page). */
            canonicalUrl?: string | null;
            /** @description The item's own doc prose, as generic nodes. */
            docs?: components["schemas"]["JsonNode"][];
            /** @description Structured metadata (name, kind, visibility, path, crate). */
            meta: components["schemas"]["JsonMeta"];
            source?: components["schemas"]["JsonNode"][];
        };
        /**
         * @description The crate list. Minimal projection of [`ListDoc`] (a soon-to-be-reworked
         *     command).
         */
        JsonList: {
            crates: components["schemas"]["JsonCrate"][];
        };
        JsonListItem: {
            content: components["schemas"]["JsonNode"][];
        };
        /** @description A macro body: its definition source verbatim. */
        JsonMacro: {
            definition: string;
        };
        JsonMeta: {
            crateName: string;
            crateVersion?: string | null;
            definedAt?: string | null;
            /** @description Lowercased item kind (`"struct"`, `"enum"`, …). */
            kind: string;
            name: string;
            /** @description `"public"`, `"private"`, `"crate"`, or `"restricted"`. */
            visibility: string;
        };
        JsonMetadataField: {
            label: string;
            value: components["schemas"]["JsonSpan"][];
        };
        JsonMethod: {
            docs?: components["schemas"]["JsonNode"][];
            isAsync?: boolean;
            isConst?: boolean;
            isUnsafe?: boolean;
            /** @description `"method"`, `"const"`, or `"type"`. */
            kind: string;
            name: string;
            /** @description Return-type spans (functions with an explicit output). */
            returns?: components["schemas"]["JsonSpan"][];
            /** @description Full display signature, the same spans the terminal renders. */
            signature: components["schemas"]["JsonSpan"][];
            /** @description `"public"`, `"crate"`, `"restricted"`, or `"default"`. */
            visibility: string;
        };
        /**
         * @description A module body: its child items as a flat list. Grouping is left to the
         *     client — each item carries the `kind` it would group under.
         */
        JsonModule: {
            items?: components["schemas"]["JsonModuleItem"][];
        };
        JsonModuleItem: {
            docs?: components["schemas"]["JsonNode"][];
            /** @description Lowercased item kind (`"struct"`, `"enum"`, `"function"`, …). */
            kind: string;
            /** @description Path as listed (bare name, or `a::b::c` when reached recursively). */
            path: string;
            /** @description Navigation target — the resolved docs.rs / std-docs URL for the child. */
            url: string;
        };
        /**
         * @description JSON mirror of [`DocumentNode`] — a faithful serialization of the
         *     presentation IR, used for the header, docs, source, opaque methods, and
         *     not-yet-modeled bodies.
         */
        JsonNode: {
            spans: components["schemas"]["JsonSpan"][];
            /** @enum {string} */
            type: "paragraph";
        } | {
            fields: components["schemas"]["JsonMetadataField"][];
            /** @enum {string} */
            type: "metadata";
        } | {
            level: components["schemas"]["HeadingLevel"];
            spans: components["schemas"]["JsonSpan"][];
            /** @enum {string} */
            type: "heading";
        } | {
            nodes: components["schemas"]["JsonNode"][];
            title?: components["schemas"]["JsonSpan"][] | null;
            /** @enum {string} */
            type: "section";
        } | {
            items: components["schemas"]["JsonListItem"][];
            /** @enum {string} */
            type: "list";
        } | {
            /**
             * @description Doctest attributes worth surfacing to a reader — `should_panic` and
             *     `compile_fail`, positive assertions that the example is a
             *     counterexample. Omitted when empty.
             */
            attrs?: string[];
            lang?: string | null;
            /**
             * @description Syntax-highlighted spans that tile the source: concatenating their
             *     `text` reconstructs the raw code (there is no separate `code` field).
             *     A span without a `class` is unstyled text (punctuation, plain
             *     identifiers, or a block whose language has no grammar).
             */
            spans: components["schemas"]["JsonCodeSpan"][];
            /** @enum {string} */
            type: "codeBlock";
        } | {
            spans: components["schemas"]["JsonSpan"][];
            /** @enum {string} */
            type: "generatedCode";
        } | {
            /** @enum {string} */
            type: "horizontalRule";
        } | {
            nodes: components["schemas"]["JsonNode"][];
            /** @enum {string} */
            type: "blockQuote";
        } | {
            header?: components["schemas"]["JsonTableCell"][] | null;
            rows: components["schemas"]["JsonTableCell"][][];
            /** @enum {string} */
            type: "table";
        } | {
            level: components["schemas"]["TruncationLevel"];
            /**
             * @description The retained nodes *after* applying `level` — a preview
             *     (`SingleLine`/`Brief`) keeps only the first block, `Full` keeps all.
             *     Truncation happens here rather than on the client so the wire payload
             *     carries the summary, not the whole essay it summarizes.
             */
            nodes: components["schemas"]["JsonNode"][];
            /**
             * @description `true` when nodes were dropped — the client's cue that a fuller body
             *     exists behind the item's navigation target.
             */
            truncated?: boolean;
            /** @enum {string} */
            type: "truncatedBlock";
        } | {
            nodes: components["schemas"]["JsonNode"][];
            show_when: components["schemas"]["ShowWhen"];
            /** @enum {string} */
            type: "conditional";
        };
        /**
         * @description A not-found result: the query and "did you mean" candidates. A JSON client
         *     distinguishes it from a found item by the `error` discriminant.
         */
        JsonNotFound: {
            /** @description Always `"notFound"`. */
            error: string;
            query: string;
            suggestions?: components["schemas"]["JsonSuggestion"][];
        };
        /**
         * @description A search outcome. `error` is set only for the no-crates-loaded case; an empty
         *     query and a query with no matches both serialize as `{ query, results: [] }`.
         */
        JsonSearch: {
            error?: string | null;
            query?: string | null;
            results?: components["schemas"]["JsonSearchResult"][];
            suggestions?: components["schemas"]["JsonSuggestion"][];
        };
        JsonSearchResult: {
            docs?: components["schemas"]["JsonNode"][];
            /** @description Lowercased item kind. */
            kind: string;
            path: string;
            /**
             * Format: float
             * @description Normalized relevance score (best result = 100).
             */
            score: number;
            url: string;
        };
        JsonSpan: {
            /**
             * @description In-app navigation target: a `::`-joined item path (e.g. `trillium::Conn`)
             *     the client routes to. Present whenever the target resolves to an item with
             *     its own page; absent for associated items, variants, and bare external URLs.
             */
            path?: string | null;
            style: components["schemas"]["SpanStyle"];
            text: string;
            /**
             * @description A link we cannot express as an item path: an external hyperlink written in
             *     the docs (a blog post, an RFC) or a link that resolved to no item. Mutually
             *     exclusive with `path` — where a path exists it *is* the navigation target,
             *     so no upstream URL is emitted beside it (see [`json_span`]).
             */
            url?: string | null;
        };
        /** @description A static body: name, type, and value expression. */
        JsonStatic: {
            name: string;
            type: components["schemas"]["JsonSpan"][];
            value: string;
        };
        JsonStruct: {
            fields?: components["schemas"]["JsonField"][];
            generics?: components["schemas"]["JsonSpan"][];
            /** Format: uint */
            hiddenFieldCount?: number;
            /** @description Inherent associated items, structurally modeled. */
            methods?: components["schemas"]["JsonMethod"][];
            name: string;
            /** @description `"plain"`, `"tuple"`, or `"unit"`. */
            shape: string;
            /** @description Trait implementations, structurally modeled. */
            traitImpls?: components["schemas"]["JsonTraitImpl"][];
            whereClause?: components["schemas"]["JsonSpan"][];
        };
        JsonSuggestion: {
            /** @description Lowercased kind of the resolved candidate, when known. */
            kind?: string | null;
            path: string;
            url?: string | null;
        };
        JsonTableCell: {
            spans: components["schemas"]["JsonSpan"][];
        };
        JsonTrait: {
            generics?: components["schemas"]["JsonSpan"][];
            /**
             * @description Every implementor in the crate, sorted by type name — not the terminal's
             *     capped preview, so a client can show the whole list. Each carries impl
             *     detail only where the impl block or its methods have their own docs.
             */
            implementors?: components["schemas"]["JsonImplementor"][];
            members?: components["schemas"]["JsonTraitMember"][];
            name: string;
            supertraits?: components["schemas"]["JsonSpan"][];
            whereClause?: components["schemas"]["JsonSpan"][];
        };
        /**
         * @description A trait implementation on a type. Carries the full structural impl —
         *     including data the terminal drops (the impl's `methods`, `providedMethods`,
         *     the negative/unsafe/synthetic flags, the blanket source type, and impl
         *     `docs`). The compact/std bucketing is a terminal concern and not serialized.
         */
        JsonTraitImpl: {
            /** @description The trait's generic arguments (`<T>` in `From<T>`). */
            args?: components["schemas"]["JsonSpan"][];
            assocTypes?: components["schemas"]["JsonImplAssocType"][];
            /** @description Blanket source type, when this came from a blanket impl. */
            blanket?: components["schemas"]["JsonSpan"][];
            docs?: components["schemas"]["JsonNode"][];
            isNegative?: boolean;
            isStd?: boolean;
            isSynthetic?: boolean;
            isUnsafe?: boolean;
            /** @description Methods / assoc consts the impl provides or overrides. */
            methods?: components["schemas"]["JsonMethod"][];
            /** @description Names of trait-default methods inherited (not overridden). */
            providedMethods?: string[];
            traitName: string;
            traitUrl?: string | null;
        };
        JsonTraitMember: {
            docs?: components["schemas"]["JsonNode"][];
            /** @description For methods: `true` if a default body is provided. */
            hasDefault?: boolean;
            /** @description `"method"`, `"const"`, or `"type"`. */
            kind: string;
            name: string;
            signature: components["schemas"]["JsonSpan"][];
        };
        /** @description A type-alias body: the aliased type (RHS of `=`) as a span sequence. */
        JsonTypeAlias: {
            aliased: components["schemas"]["JsonSpan"][];
            name: string;
        };
        /**
         * @description Crate-name typeahead results: the highest-ranked crates whose names start
         *     with the query prefix, in rank order.
         */
        JsonTypeahead: {
            query: string;
            results: components["schemas"]["JsonTypeaheadEntry"][];
            /**
             * Format: uint
             * @description Exact number of crates matching the prefix; `results.len() < total`
             *     means the list was truncated to the requested limit.
             */
            total: number;
        };
        JsonTypeaheadEntry: {
            name: string;
            /**
             * @description The crate's crates.io default version (typically the latest stable
             *     non-yanked release), up to ~a day stale.
             */
            version: string;
        };
        /**
         * @description A union body. Mirrors [`JsonStruct`] minus the `shape` (a union is always
         *     named fields).
         */
        JsonUnion: {
            fields?: components["schemas"]["JsonField"][];
            generics?: components["schemas"]["JsonSpan"][];
            /** Format: uint */
            hiddenFieldCount?: number;
            methods?: components["schemas"]["JsonMethod"][];
            name: string;
            traitImpls?: components["schemas"]["JsonTraitImpl"][];
            whereClause?: components["schemas"]["JsonSpan"][];
        };
        JsonVariant: {
            docs?: components["schemas"]["JsonNode"][];
            /** @description Struct-variant named fields. */
            fields?: components["schemas"]["JsonVariantField"][];
            name: string;
            /** @description `"plain"`, `"tuple"`, or `"struct"`. */
            shape: string;
            /** @description Tuple-variant field types, each a span sequence. */
            tupleFields?: components["schemas"]["JsonSpan"][][];
        };
        JsonVariantField: {
            name: string;
            type: components["schemas"]["JsonSpan"][];
        };
        /** @description Condition for when to show content (used by Conditional node) */
        ShowWhen: "Always" | "Interactive" | "NonInteractive";
        /**
         * @description Semantic styling categories for Rust code elements
         * @enum {string}
         */
        SpanStyle: "Keyword" | "TypeName" | "FunctionName" | "FieldName" | "Lifetime" | "Generic" | "Plain" | "Punctuation" | "Operator" | "Comment" | "InlineRustCode" | "InlineCode" | "Strong" | "Emphasis" | "Strikethrough";
        /** @description Truncation level hint for renderers */
        TruncationLevel: "SingleLine" | "Brief" | "Full";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
